CREATE TABLE MAPPING_PAR_REF_AIRPORT (
AIRPORT_ID INT,
PARAMETER_ID INT,
VALID_FROM DATE,
VALID_TO DATE
);



CREATE TABLE  MAPPING_PAR_REF_GROUND_HANDLER (
GROUND_HANDLER_ID INT
PARAMETER_ID INT
VALID_FROM DATE,
VALID_TO DATE
);


CREATE TABLE PAR_AIRPORT (
PARAMETER_ID INT,
PARAMETER_NAME VARCHAR(255),
PARAMETER_DESCRIPTION VARCHAR(255),
PARAMETER_VALUE FLOAT,
VALID_FROM DATE,
VALID_TO DATE
);


CREATE TABLE PAR_GROUND_HANDLER (
PARAMETER_ID INT,
PARAMETER_NAME VARCHAR(255),
PARAMETER_DESCRIPTION VARCHAR(255),
PARAMETER_VALUE FLOAT,
VALID_FROM DATE,
VALID_TO DATE
);